name: Testing
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8' 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install django
          pip install coverage

      - name: Run migrations and tests
        working-directory: WebApp
        env:
          DJANGO_SETTINGS_MODULE: WebApp.settings
        run: |
          python manage.py makemigrations
          python manage.py migrate
          coverage run --source='.' manage.py test
          coverage report
